name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: cd client && npm ci
    - name: Set up the environment
      run: |
        echo "VITE_API_URL=https://${{ secrets.API_URL }}/vartarvipavag/api" >> client/.env
    - run: cd client && npm run build
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './client/dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: github.event_name == 'push'
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: cd server && npm ci
    - run: cd server && npm run build
